apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default
subjects:
- kind: ServiceAccount
  name: mynewsa
  namespace: default
roleRef:
  kind: Role
  name: pod-read
  apiGroup: rbac.authorization.k8s.io
